// =========================================================
// Generated by manage.js — edit files in content/ or run 'node manage.js'
// =========================================================

const WRITEUPS = [];

const PROJECTS = [];

const NOTES_TREE = [];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { WRITEUPS, PROJECTS, NOTES_TREE };
}
